export const ADD_NEW_SLIDER_ITEM = "ADD_NEW_SLIDER_ITEM";
export const EDIT_SLIDER_ITEM = "EDIT_SLIDER_ITEM";
export const SET_SLIDER = "SET_SLIDER";
export const DELETE_SLIDER_ITEM = "DELETE_SLIDER_ITEM";